---
# This playbook is a template, before use repalce roles 'common' to your role, Optional deletion of useless roles, such as nginx

- name: Some desc for you job
  hosts:
    - all
  remote_user: root

  roles:
    - common

- name: Some desc for you job
  hosts:
    - nginx_server
  remote_user: root

  roles:
    - nginx
